# Generated by Django 4.2.29 on 2026-07-26 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('report_type', models.CharField(choices=[('expense_summary', 'Expense Summary'), ('category_analysis', 'Category Analysis'), ('trend_analysis', 'Trend Analysis'), ('budget_variance', 'Budget vs Actual'), ('group_summary', 'Group Summary'), ('monthly_summary', 'Monthly Summary')], max_length=20)),
                ('format', models.CharField(choices=[('json', 'JSON'), ('csv', 'CSV'), ('pdf', 'PDF')], default='json', max_length=10)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10)),
                ('parameters', models.JSONField(default=dict)),
                ('last_sent', models.DateTimeField(blank=True, null=True)),
                ('next_send', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['next_send'],
            },
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='report',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
        migrations.AddField(
            model_name='report',
            name='format',
            field=models.CharField(choices=[('json', 'JSON'), ('csv', 'CSV'), ('pdf', 'PDF')], default='json', max_length=10),
        ),
        migrations.AddField(
            model_name='report',
            name='is_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='report',
            name='parameters',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('expense_summary', 'Expense Summary'), ('category_analysis', 'Category Analysis'), ('trend_analysis', 'Trend Analysis'), ('budget_variance', 'Budget vs Actual'), ('group_summary', 'Group Summary'), ('monthly_summary', 'Monthly Summary')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['user', 'report_type'], name='reports_rep_user_id_f11f57_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['created_at'], name='reports_rep_created_a6aabf_idx'),
        ),
        migrations.AddField(
            model_name='scheduledreport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='scheduledreport',
            index=models.Index(fields=['user', 'is_active'], name='reports_sch_user_id_369fc7_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledreport',
            index=models.Index(fields=['next_send'], name='reports_sch_next_se_390db7_idx'),
        ),
    ]
