# Generated by Django 4.2.29 on 2026-03-13 09:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalyRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('threshold_multiplier', models.FloatField(default=2.0)),
                ('lookback_days', models.IntegerField(default=30)),
                ('min_amount', models.DecimalField(decimal_places=2, default=10.0, max_digits=10)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categories', models.ManyToManyField(blank=True, to='categories.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomaly_rules', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SpendingPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=20)),
                ('average_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('median_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('std_deviation', models.FloatField()),
                ('frequency', models.IntegerField()),
                ('trend_direction', models.FloatField()),
                ('seasonal_factors', models.TextField(blank=True, null=True)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spending_patterns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'calculated_at'], name='analytics_s_user_id_ed6880_idx')],
                'unique_together': {('user', 'category', 'period')},
            },
        ),
        migrations.CreateModel(
            name='FinancialHealthMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('budget_adherence_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('spending_stability_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('savings_rate_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('expense_consistency_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('overall_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('total_monthly_expenses', models.DecimalField(decimal_places=2, max_digits=10)),
                ('average_daily_spending', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expense_volatility', models.FloatField()),
                ('recommendations', models.TextField(blank=True, default='[]')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-calculated_at'],
                'indexes': [models.Index(fields=['user', '-calculated_at'], name='analytics_f_user_id_ac8501_idx')],
            },
        ),
    ]
