# Generated by Django 4.2.29 on 2026-07-26 17:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anomalyrule',
            name='name',
            field=models.CharField(default='Default Rule', max_length=100),
        ),
        migrations.AlterField(
            model_name='financialhealthmetric',
            name='average_daily_spending',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='financialhealthmetric',
            name='budget_adherence_score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='financialhealthmetric',
            name='expense_consistency_score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='financialhealthmetric',
            name='expense_volatility',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='financialhealthmetric',
            name='overall_score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='financialhealthmetric',
            name='savings_rate_score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='financialhealthmetric',
            name='spending_stability_score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='financialhealthmetric',
            name='total_monthly_expenses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='spendingpattern',
            name='average_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='spendingpattern',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.category'),
        ),
        migrations.AlterField(
            model_name='spendingpattern',
            name='frequency',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='spendingpattern',
            name='median_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='spendingpattern',
            name='std_deviation',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='spendingpattern',
            name='trend_direction',
            field=models.FloatField(default=0),
        ),
    ]
