# Generated by Django 4.2.29 on 2026-03-13 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0001_initial'),
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='groups.group'),
        ),
        migrations.AddField(
            model_name='expense',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='expenses.paymentmethod'),
        ),
        migrations.AddField(
            model_name='expense',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='paymentmethod',
            unique_together={('user', 'name')},
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['user', 'date'], name='expenses_ex_user_id_713a9d_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['user', 'category', 'date'], name='expenses_ex_user_id_8a0d73_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['user', 'is_anomaly'], name='expenses_ex_user_id_38c6f9_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['group', 'date'], name='expenses_ex_group_i_f6bb8c_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['payment_status'], name='expenses_ex_payment_cfbab8_idx'),
        ),
    ]
