# Generated by Django 4.2.29 on 2026-07-26 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_initial'),
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recurring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringexpense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='recurringexpense',
            name='auto_create',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='recurringexpense',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_expenses', to='categories.category'),
        ),
        migrations.AlterField(
            model_name='recurringexpense',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='expenses.paymentmethod'),
        ),
        migrations.AlterField(
            model_name='recurringexpense',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recurringexpenselog',
            name='expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='expenses.expense'),
        ),
    ]
