# Generated by Django 4.2.29 on 2026-08-02 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recurring', '0002_alter_recurringexpense_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringexpense',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
